// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXQO4ZrpxgeR290C_Inq2YCKhtIYezwM',
    appId: '1:981834090674:web:4b84f4287618f0b91421ab',
    messagingSenderId: '981834090674',
    projectId: 'pokedex-22554',
    authDomain: 'pokedex-22554.firebaseapp.com',
    storageBucket: 'pokedex-22554.appspot.com',
    measurementId: 'G-6VLZTMMQ06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADSWwA7yx-l9d8F6GQ3OfzvbBvxpZrZwo',
    appId: '1:981834090674:android:7ecd3b935f2ee3701421ab',
    messagingSenderId: '981834090674',
    projectId: 'pokedex-22554',
    storageBucket: 'pokedex-22554.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0G2ZP-KbhbFyRo7X0hyOF7NovBeb7ihI',
    appId: '1:981834090674:ios:bafbff2be0e8eebf1421ab',
    messagingSenderId: '981834090674',
    projectId: 'pokedex-22554',
    storageBucket: 'pokedex-22554.appspot.com',
    iosClientId: '981834090674-ncrusv7o95nigfotlkejv9mun58n7h5p.apps.googleusercontent.com',
    iosBundleId: 'id.ac.students.utdi.agudimus46',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0G2ZP-KbhbFyRo7X0hyOF7NovBeb7ihI',
    appId: '1:981834090674:ios:bafbff2be0e8eebf1421ab',
    messagingSenderId: '981834090674',
    projectId: 'pokedex-22554',
    storageBucket: 'pokedex-22554.appspot.com',
    iosClientId: '981834090674-ncrusv7o95nigfotlkejv9mun58n7h5p.apps.googleusercontent.com',
    iosBundleId: 'id.ac.students.utdi.agudimus46',
  );
}
